api:
  key: ${CHS_API_KEY}
  url: ${API_URL}

aws:
  accessKeyId: ${AWS_ACCESS_KEY_ID}
  region: ${ENV_REGION_AWS}
  secretAccessKey: ${AWS_SECRET_ACCESS_KEY}

barcodeGenerator:
  host: ${BARCODE_SERVICE_URL}

cdn:
  host: ${CDN_HOST}

chips:
  host: ${CHIPS_REST_SERVICE_URL}
  retryLimit: ${DISSOLUTION_CHIPS_RETRY_LIMIT}
  submissionLimit: ${DISSOLUTION_CHIPS_SUBMISSION_LIMIT}
  retryDelayMinutes: ${DISSOLUTION_CHIPS_RETRY_DELAY}

companyProfile:
  host: ${CHS_COMPANY_PROFILE_API_LOCAL_URL}

dissolution:
  pdfBucket: ${DISSOLUTION_PDF_BUCKET}

documentRender:
  host: ${DOCUMENT_RENDER_SERVICE_HOST}

email:
  chsFinanceEmail: ${CHS_FINANCE_EMAIL}
  chsSupportEmail: ${CHS_SUPPORT_EMAIL}

env:
  name: ${ENV_NAME}
  chsUrl: ${CHS_URL}

kafka:
  api:
    url: ${CHS_KAFKA_API_URL:http://localhost:8888}
  broker:
    addr: ${KAFKA_BROKER_ADDR}
  config:
    acks: ${KAFKA_CONFIG_ACKS}
    retries: ${KAFKA_CONFIG_RETRIES}
    isRoundRobin: ${KAFKA_CONFIG_IS_ROUND_ROBIN}
  schema:
    registry:
      url: ${SCHEMA_REGISTRY_URL}
    uri:
      email-send: ${EMAIL_SCHEMA_URI}

logging:
  namespace: dissolution-api

payments:
  url: ${PAYMENTS_API_URL}

server:
  port: 3001

spring:
  data:
    mongodb:
      uri: ${DISSOLUTIONS_API_MONGODB_URL}

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      path-mapping:
        health: /dissolution-request/healthcheck
  endpoint:
    health:
      show-details: never
      enabled: true
