api:
  key: ${CHS_API_KEY}
  url: ${API_URL}

barcodeGenerator:
  host: ${BARCODE_SERVICE_URL}

cdn:
  host: ${CDN_HOST}

companyProfile:
  host: ${CHS_COMPANY_PROFILE_API_LOCAL_URL}

dissolution:
  pdfBucket: ${DISSOLUTION_PDF_BUCKET}

documentRender:
  host: ${DOCUMENT_RENDER_SERVICE_HOST}

env:
  name: ${ENV_NAME}
  chsUrl: ${CHS_URL}

logging:
  level:
    root: ${LOGLEVEL}

server:
  port: 3001

spring:
  data:
    mongodb:
      uri: ${DISSOLUTIONS_API_MONGODB_URL}
kafka:
  config:
    acks: ${KAFKA_CONFIG_ACKS}
    retries: ${KAFKA_CONFIG_RETRIES}
    isRoundRobin: ${KAFKA_CONFIG_IS_ROUND_ROBIN}
  schema:
    registry:
      url: ${SCHEMA_REGISTRY_URL}
    uri:
      email-send: ${EMAIL_SCHEMA_URI}
