api:
  key: ${CHS_API_KEY}
  url: ${API_URL}

barcodeGenerator:
  host: ${BARCODE_SERVICE_URL}

companyProfile:
  host: ${CHS_COMPANY_PROFILE_API_LOCAL_URL}

logging:
  level:
    ROOT: ${LOGLEVEL}
server:
  port: 3001
spring:
  data:
    mongodb:
      uri: ${DISSOLUTIONS_API_MONGODB_URL}
