api:
  key: ${CHS_API_KEY}
  url: ${API_URL}

barcodeGenerator:
  host: ${BARCODE_SERVICE_URL}

cdn:
  host: ${CDN_HOST}

dissolution:
  pdfBucket: ${DISSOLUTION_PDF_BUCKET}

documentRender:
  host: ${DOCUMENT_RENDER_SERVICE_HOST}

env:
  name: ${ENV_NAME}

logging:
  level:
    root: ${LOGLEVEL}

server:
  port: 3001

spring:
  data:
    mongodb:
      uri: ${DISSOLUTIONS_API_MONGODB_URL}
